name = "Afi"
author = "Afi"
prefix = "afi"
mainprefix = "x"

[files]
include = [
    "mod.cpp",
    "data/**",
    "addons/swt_markers_a3.pbo",
    "addons/swt_markers_a3.pbo.afi_1732216694.bisign",
    # "addons/BH_checkLOS.pbo",
    # "addons/BH_checkLOS.pbo.afi_1732216694.bisign",
]

[version]
git_hash = 0 

[binarize]
enabled = true 

[lint.sqf]
enabled = true

[hemtt.launch.default]
workshop = [
    "1291778160",
    "450814997", # CBA
    "463939057", # ACE
    # "894678801", # TFAR
]
parameters = [
    "-noPause",
    "C:\\Users\\mikal\\Documents\\Arma 3 - Other Profiles\\Tuntematon\\missions\\testMission.VR\\mission.sqm", # Launch into existing Editor Mission - \\ needed
]

[hemtt.launch.all]
workshop = [
    "450814997", # CBA_A3
    "463939057", # ACE
    "843425103", # RHS AFRF Workshop ID
    "843577117", # RHS USAF Workshop ID
    "843593391", # RHS GREF Workshop ID
    "843632231", # RHS SAF  Workshop ID
    "1673456286", # 3CB FACTIONS Workshop ID
    "893349825", # 3CB Vehicles Workshop ID
    "894678801", # TFAR
]
parameters = [
    "-noPause",
    #"C:\\Users\\mikal\\Documents\\Arma 3 - Other Profiles\\Tuntematon\\missions\\igla.altis\\mission.sqm", # Launch into existing Editor Mission - \\ needed
]

[hemtt.release]
folder = "afi"

[hemtt.launch.server]
workshop = [
    "450814997", # CBA_A3
    "463939057", # ACE
    "843425103", # RHS AFRF Workshop ID
    "843577117", # RHS USAF Workshop ID
    "843593391", # RHS GREF Workshop ID
    "843632231", # RHS SAF  Workshop ID
    "1673456286", # 3CB FACTIONS Workshop ID
    "893349825", # 3CB Vehicles Workshop ID
    "894678801", # TFAR
]
parameters = [
    "-server",
    "-port=2302",
    "-filePatching",
    "-cfg=C:\\Users\\mikal\\Documents\\GitHub\\AFI-Tweaks\\server\\server_basic.cfg",
    "-config=C:\\Users\\mikal\\Documents\\GitHub\\AFI-Tweaks\\server\\server_config.cfg",
]

[hemtt.launch.player]
workshop = [
    "450814997", # CBA_A3
    "463939057", # ACE
    "843425103", # RHS AFRF Workshop ID
    "843577117", # RHS USAF Workshop ID
    "843593391", # RHS GREF Workshop ID
    "843632231", # RHS SAF  Workshop ID
    "1673456286", # 3CB FACTIONS Workshop ID
    "893349825", # 3CB Vehicles Workshop ID
    "894678801", # TFAR
]
parameters = [
    "-debug",
    "-filePatching",
    "-world=empty",
    "-noPause",
    "-noPauseAudio",
    "-connect=localHost",
    "-port=2302",
    "-window",
]