name = "Afi Tweaks"
author = "Tuntematon"
prefix = "afiTweaks"
mainprefix = "x"

[files]
include = [
    "mod.cpp",
    "data/**",
]

[version]
git_hash = 0 

[binarize]
enabled = true 

[lint.sqf]
enabled = true

[hemtt.launch.default]
workshop = [
    "1291778160",
    "450814997", # CBA
    "463939057", # ACE
    # "894678801", # TFAR
]
parameters = [
    "-filePatching",
    "-noPause",
    #"C:\\Users\\mikal\\Documents\\Arma 3 - Other Profiles\\Tuntematon\\missions\\TUN_Respawn_System.Stratis\\mission.sqm", # Launch into existing Editor Mission - \\ needed
]

[hemtt.release]
folder = "afi_tweaks"
